// LOGIN Signup actions
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_FAILURAE = 'LOGIN_FAILURAE';
export const SET_BILLS_DATA_ON_LOGIN = 'SET_BILLS_DATA_ON_LOGIN';
export const SET_USERS_DATA_ON_LOGIN = 'SET_USERS_DATA_ON_LOGIN';

// Dish split page actions
export const SAVE_DISH_SPLIT = 'SAVE_DISH_SPLIT';
export const CANCEL_DISH_SPLIT = 'CANCEL_DISH_SPLIT';

// BillSplit data process
export const SAVE_BILL_RECORD = 'SAVE_BILL_RECORD';
export const SET_CURRENT_PEOPLE = 'SET_CURRENT_PEOPLE';
export const SET_PAID_BY = 'SET_PAID_BY';
export const ADD_NEW_USER_TO_STORE = 'ADD_NEW_USER_TO_STORE';

// Bill split page interactions
export const CHANGE_BILL_NAME = 'CHANGE_BILL_NAME';
export const CHANGE_BILL_AMOUNT = 'CHANGE_BILL_AMOUNT';
export const SHOW_PEOPLE_INVOVLVED_MODAL = 'SHOW_PEOPLE_INVOVLVED_MODAL';

// Data base related actions
export const BILL_PERSIST_SUCCESS = 'BILL_PERSIST_SUCCESS';
export const FIREBASE_QUERY_ERROR = 'FIREBASE_QUERY_ERROR';
export const USER_PERSIST_SUCCESS = 'USER_PERSIST_SUCCESS';
export const USER_PERSIST_FAILUARE = 'USER_PERSIST_FAILUARE';

// Dash Board actions
export const SET_DASHBOARD_LOADING = 'SET_DASHBOARD_LOADING';
export const SET_BILL_FOR_EDIT = 'SET_BILL_FOR_EDIT';
export const ADD_NEW_BILL = 'ADD_NEW_BILL';
