export const SAVE_DISH_SPLIT = 'SAVE_DISH_SPLIT';
export const CANCEL_DISH_SPLIT = 'CANCEL_DISH_SPLIT';


export const ADD_NEW_BILL = 'ADD_NEW_BILL';
export const SAVE_BILL_RECORD = 'SAVE_BILL_RECORD';
export const SET_BILL_FOR_EDIT = 'SET_BILL_FOR_EDIT';

export const CHANGE_BILL_NAME = 'CHANGE_BILL_NAME';
export const CHANGE_BILL_AMOUNT = 'CHANGE_BILL_AMOUNT';
export const SET_PAID_BY = 'SET_PAID_BY';

export const BILL_PERSIST_SUCCESS = 'BILL_PERSIST_SUCCESS';
